---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.16.9, namelong: vg-moloch-01.local, nameshort: vg-moloch-01 }
  - { ip: 192.168.16.10, namelong: vg-moloch-02.local, nameshort: vg-moloch-02 }
  - { ip: 192.168.16.11, namelong: vg-moloch-03.local, nameshort: vg-moloch-03 }
  when: add_host_entries
