---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
- name: "Install moloch"
  gather_facts: true
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  hosts: vg-moloch-01
  become: yes
  roles:
    - moloch
- name: "Install moloch"
  gather_facts: true
  hosts: vg-moloch-02
  become: yes
  roles:
    - moloch
